import { FormControlUnstyled } from "@mui/core";
import React from "react";
import "../styles/Footer.css"

class Footer extends React.Component{
    render(){
        return(
            <div>
                <svg width="100%" height="230">
                    <g>
                       <g className="border-Lines">
                         <line 
                              x1="0"
                              y1="225"
                              x2="100%"
                              y2="225"
                              height="25"
                              stroke="black"
                              stroke-width="8"
                         ></line>
                         <line 
                              x1="0"
                              y1="125"
                              x2="100%"
                              y2="125"
                              height="25"
                              stroke="black"
                              stroke-width="8"
                         ></line>
                       </g>
                       <line 
                              x1="5"
                              y1="225"
                              x2="110"
                              y2="125"
                              height="12"
                              stroke="black"
                              stroke-width="3"
                        ></line>
                        <line 
                              x1="215"
                              y1="225"
                              x2="105"
                              y2="125"
                              height="12"
                              stroke="black"
                              stroke-width="3"
                        ></line>
                        <line 
                              x1="215"
                              y1="225"
                              x2="315"
                              y2="125"
                              height="12"
                              stroke="black"
                              stroke-width="3"
                        ></line>
                        <line 
                              x1="410"
                              y1="220"
                              x2="310"
                              y2="125"
                              height="12"
                              stroke="black"
                              stroke-width="3"
                        ></line>
                        <line 
                              x1="505"
                              y1="125"
                              x2="410"
                              y2="220"
                              height="12"
                              stroke="black"
                              stroke-width="3"
                        ></line>
                        <line 
                              x1="510"
                              y1="125"
                              x2="615"
                              y2="220"
                              height="12"
                              stroke="black"
                              stroke-width="3"
                        ></line>
                        <line 
                              x1="705"
                              y1="125"
                              x2="615"
                              y2="220"
                              height="12"
                              stroke="black"
                              stroke-width="3"
                        ></line>
                        <line 
                              x1="710"
                              y1="125"
                              x2="815"
                              y2="220"
                              height="12"
                              stroke="black"
                              stroke-width="3"
                        ></line>
                        <line 
                              x1="910"
                              y1="125"
                              x2="815"
                              y2="220"
                              height="12"
                              stroke="black"
                              stroke-width="3"
                        ></line>
                        <line 
                              x1="910"
                              y1="125"
                              x2="1015"
                              y2="220"
                              height="12"
                              stroke="black"
                              stroke-width="3"
                        ></line>
                        <line 
                              x1="1110"
                              y1="125"
                              x2="1015"
                              y2="220"
                              height="12"
                              stroke="black"
                              stroke-width="3"
                        ></line>
                        <line 
                              x1="1110"
                              y1="125"
                              x2="1215"
                              y2="220"
                              height="12"
                              stroke="black"
                              stroke-width="3"
                        ></line>
                        <line 
                              x1="1310"
                              y1="125"
                              x2="1215"
                              y2="220"
                              height="12"
                              stroke="black"
                              stroke-width="3"
                        ></line>
                        <line 
                              x1="1310"
                              y1="125"
                              x2="1415"
                              y2="220"
                              height="12"
                              stroke="black"
                              stroke-width="3"
                        ></line>
                    </g>
                    <g>
                        <polygon
                          fill="Teal"
                          stroke="#000000"
                          stroke-width="2"
                          stroke-miterlimit="20"
                          points=" 180,220 40,220, 110,155 "
                        />
                        <polygon
                          fill="Peru
                          "
                          stroke="#000000"
                          stroke-width="2"
                          stroke-miterlimit="20"
                          points=" 380,220 245,220, 310,155 "
                        />
                        <polygon
                          fill="IndianRed"
                          stroke="#000000"
                          stroke-width="2"
                          stroke-miterlimit="20"
                          points=" 580,220 445,220, 510,155 "
                        />
                        <polygon
                          fill="Teal"
                          stroke="#000000"
                          stroke-width="2"
                          stroke-miterlimit="20"
                          points=" 780,220 645,220, 710,155 "
                        />
                        <polygon
                          fill="Teal"
                          stroke="#000000"
                          stroke-width="2"
                          stroke-miterlimit="20"
                          points=" 980,220 845,220, 910,155 "
                        />
                        <polygon
                          fill="Teal"
                          stroke="#000000"
                          stroke-width="2"
                          stroke-miterlimit="20"
                          points=" 1180,220 1045,220, 1110,155 "
                        />
                        <polygon
                          fill="Teal"
                          stroke="#000000"
                          stroke-width="2"
                          stroke-miterlimit="20"
                          points=" 1380,220 1245,220, 1310,155 "
                        />
                    </g>
                    <g className="upper-Triangles"> 
                        <polygon
                          fill="Teal"
                          stroke="#000000"
                          stroke-width="2"
                          stroke-miterlimit="20"
                          points=" 180,220 40,220, 110,155 "
                        />
                        <polygon
                          fill="Peru
                          "
                          stroke="#000000"
                          stroke-width="2"
                          stroke-miterlimit="20"
                          points=" 380,220 245,220, 310,155 "
                        />
                        <polygon
                          fill="IndianRed"
                          stroke="#000000"
                          stroke-width="2"
                          stroke-miterlimit="20"
                          points=" 580,220 445,220, 510,155 "
                        />
                        <polygon
                          fill="Teal"
                          stroke="#000000"
                          stroke-width="2"
                          stroke-miterlimit="20"
                          points=" 780,220 645,220, 710,155 "
                        />
                        <polygon
                          fill="Teal"
                          stroke="#000000"
                          stroke-width="2"
                          stroke-miterlimit="20"
                          points=" 980,220 845,220, 910,155 "
                        />
                        <polygon
                          fill="Teal"
                          stroke="#000000"
                          stroke-width="2"
                          stroke-miterlimit="20"
                          points=" 1180,220 1045,220, 1110,155 "
                        />
                        <polygon
                          fill="Teal"
                          stroke="#000000"
                          stroke-width="2"
                          stroke-miterlimit="20"
                          points=" 1380,220 1245,220, 1310,155 "
                        />
                    </g>
                </svg>
            </div>
        )
    }
}

export default Footer